services:
  # RAG Testing API
  rag-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-service
    env_file:
      - .env
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - embeddings_cache:/app/.cache
    extra_hosts:
      - "host.docker.internal:host-gateway" # Enable host.docker.internal on Linux
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000

volumes:
  embeddings_cache:
    driver: local
